In [1]:
import pandas as pd 
import numpy as np 
import os 
import pandas as pd 
import numpy as np 
import os
import tensorflow as tf 
import cv2
from sklearn.model_selection import train_test_split
from tensorflow import keras 
from sklearn.preprocessing import MinMaxScaler
import joblib
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
import matplotlib.pyplot as plt 


### ML flow libaries 

##### Task 2
import numpy as np
from tensorflow.keras.models import *
from tensorflow.keras.layers import *
from sklearn.preprocessing import LabelEncoder
from tensorflow.keras.utils import to_categorical
import itertools  
from tensorflow.keras.callbacks import EarlyStopping
from sklearn.metrics import classification_report, confusion_matrix
from tensorflow.keras.applications.vgg16 import VGG16, preprocess_input
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from sklearn.metrics import classification_report, confusion_matrix
import matplotlib.pyplot as plt

In [2]:
#### Teams Data 
data = pd.read_csv('Spain/matches.csv')
data

timestamp              date_GMT    status  attendance   home_team_name  \
0    1660330800  Aug 12 2022 - 7:00pm  complete         NaN       CA Osasuna   
1    1660402800  Aug 13 2022 - 3:00pm  complete     18859.0    Celta de Vigo   
2    1660410000  Aug 13 2022 - 5:00pm  complete         NaN  Real Valladolid   
3    1660417200  Aug 13 2022 - 7:00pm  complete         NaN     FC Barcelona   
4    1660491000  Aug 14 2022 - 3:30pm  complete     16570.0            Cádiz   
..          ...                   ...       ...         ...              ...   
375  1685905200  Jun 04 2023 - 7:00pm  complete         NaN       Real Betis   
376  1685905200  Jun 04 2023 - 7:00pm  complete         NaN    Celta de Vigo   
377  1685905200  Jun 04 2023 - 7:00pm  complete     25517.0  Real Valladolid   
378  1685905200  Jun 04 2023 - 7:00pm  complete     54087.0         Elche CF   
379  1685905200  Jun 04 2023 - 7:00pm  complete         NaN     RCD Espanyol   

     away_team_name                             referee  Game Week  \
0        Sevilla FC             Carlos Del Cerro Grande          1   
1      RCD Espanyol            Miguel Ángel Ortiz Arias          1   
2        Villarreal                  Mario Melero López          1   
3    Rayo Vallecano  Alejandro José Hernández Hernández          1   
4     Real Sociedad       Isidro Díaz de Mera Escuderos          1   
..              ...                                 ...        ...   
375     Valencia CF               Javier Alberola Rojas         38   
376    FC Barcelona            Juan Luis Pulido Santana         38   
377       Getafe CF           José Luis Munuera Montero         38   
378           Cádiz                   Jesús Gil Manzano         38   
379         Almería                    César Soto Grado         38   

     Pre-Match PPG (Home)  Pre-Match PPG (Away)  ...  odds_ft_home_team_win  \
0                    0.00                  0.00  ...                   3.27   
1                    0.00                  0.00  ...                   1.88   
2                    0.00                  0.00  ...                   3.80   
3                    0.00                  0.00  ...                   1.20   
4                    0.00                  0.00  ...                   3.15   
..                    ...                   ...  ...                    ...   
375                  1.72                  0.67  ...                   2.90   
376                  1.33                  2.22  ...                   2.90   
377                  1.50                  0.78  ...                   2.15   
378                  0.78                  0.78  ...                   2.62   
379                  1.00                  0.39  ...                   3.00   

     odds_ft_draw  odds_ft_away_team_win  odds_ft_over15  odds_ft_over25  \
0            3.08                   2.13            1.47            2.30   
1            3.70                   4.04            1.33            1.98   
2            3.65                   1.95            1.32            1.91   
3            7.00                  13.55            1.15            1.46   
4            3.28                   2.54            1.45            2.30   
..            ...                    ...             ...             ...   
375          3.25                   2.45            1.20            2.03   
376          3.60                   2.30            1.25            1.63   
377          3.30                   3.40            1.39            2.19   
378          3.25                   2.70            1.25            1.87   
379          3.50                   2.30            1.14            1.51   

     odds_ft_over35  odds_ft_over45  odds_btts_yes odds_btts_no  \
0              4.75           10.00           2.00         1.75   
1              3.60            7.00           1.80         1.95   
2              3.50            6.50           1.75         2.00   
3              2.28            3.75           2.10         1.67   
4      

In [3]:
skinType = 'Celta de Vigo'

skinT = data.iloc[:, 4]
Tdf = data.groupby(skinT)
home = Tdf.get_group(skinType)

home

timestamp               date_GMT    status  attendance home_team_name  \
1    1660402800   Aug 13 2022 - 3:00pm  complete     18859.0  Celta de Vigo   
14   1661025600   Aug 20 2022 - 8:00pm  complete     15681.0  Celta de Vigo   
30   1662145200   Sep 02 2022 - 7:00pm  complete     14510.0  Celta de Vigo   
66   1664720100   Oct 02 2022 - 2:15pm  complete         NaN  Celta de Vigo   
85   1665921600  Oct 16 2022 - 12:00pm  complete         NaN  Celta de Vigo   
109  1666638000   Oct 24 2022 - 7:00pm  complete      9774.0  Celta de Vigo   
123  1667669400   Nov 05 2022 - 5:30pm  complete         NaN  Celta de Vigo   
144  1672424100   Dec 30 2022 - 6:15pm  complete         NaN  Celta de Vigo   
160  1673640000   Jan 13 2023 - 8:00pm  complete         NaN  Celta de Vigo   
185  1675013400   Jan 29 2023 - 5:30pm  complete         NaN  Celta de Vigo   
205  1676214900   Feb 12 2023 - 3:15pm  complete     15842.0  Celta de Vigo   
226  1677424500   Feb 26 2023 - 3:15pm  complete         NaN  Celta de Vigo   
243  1678555800   Mar 11 2023 - 5:30pm  complete     14451.0  Celta de Vigo   
265  1680436800  Apr 02 2023 - 12:00pm  complete         NaN  Celta de Vigo   
289  1681758000   Apr 17 2023 - 7:00pm  complete         NaN  Celta de Vigo   
305  1682539200   Apr 26 2023 - 8:00pm  complete         NaN  Celta de Vigo   
335  1684065600  May 14 2023 - 12:00pm  complete         NaN  Celta de Vigo   
350  1684863000   May 23 2023 - 5:30pm  complete         NaN  Celta de Vigo   
376  1685905200   Jun 04 2023 - 7:00pm  complete         NaN  Celta de Vigo   

           away_team_name                             referee  Game Week  \
1            RCD Espanyol            Miguel Ángel Ortiz Arias          1   
14            Real Madrid                   Jesús Gil Manzano          2   
30                  Cádiz            Juan Luis Pulido Santana          4   
66             Real Betis                    César Soto Grado          7   
85          Real Sociedad          Guillermo Cuadra Fernández          9   
109             Getafe CF              Pablo González Fuertes         11   
123            CA Osasuna              Jorge Figueroa Vázquez         13   
144            Sevilla FC        Ricardo De Burgos Bengoetxea         15   
160            Villarreal               Javier Alberola Rojas         17   
185  Athletic Club Bilbao       Isidro Díaz de Mera Escuderos         19   
205       Atlético Madrid              Jorge Figueroa Vázquez         21   
226       Real Valladolid        Ricardo De Burgos Bengoetxea         23   
243        Rayo Vallecano            Juan Luis Pulido Santana         25   
265               Almería  Alejandro José Hernández Hernández         27   
289          RCD Mallorca            Miguel Ángel Ortiz Arias         29   
305              Elche CF       Isidro Díaz de Mera Escuderos         31   
335           Valencia CF                    César Soto Grado         34   
350             Girona FC          Antonio Miguel Mateu Lahoz         36   
376          FC Barcelona            Juan Luis Pulido Santana         38   

     Pre-Match PPG (Home)  Pre-Match PPG (Away)  ...  odds_ft_home_team_win  \
1                    0.00                  0.00  ...                   1.88   
14                   1.00                  3.00  ...                   4.25   
30                   0.50                  0.00  ...                   1.72   
66                   1.33                  1.50  ...                   2.50   
85                   1.75                  2.25  ...                   2.40   
109                  1.40                  1.00  ...                   1.85   
123                  1.33                  1.00  ...                   2.00   
144                  1.14                  1.14  ...                   2.20   
160                  1.13                  1.22  ...                   2.74   
185                  1.11                  1.13  ...                   2.84   
205                  1.30          

In [4]:
status_home  = []

hg = home['home_team_goal_count'].tolist()
ag = home['away_team_goal_count'].tolist()


for i, hgx in enumerate(hg):
    agx = ag[i]
    if hgx > agx:
        status = 'Win'
        status_home.append(status)
    elif hgx < agx:
        status_l = 'Loss'
        status_home.append(status_l)
    else :
        status_d = 'Draw'
        status_home.append(status_d)

In [5]:
home.insert(11, "Status_home", status_home, True)

In [103]:
#home.to_csv('EPL_Liverpool.csv')

In [2]:
df = pd.read_csv('EPL_Liverpool.csv')
df

home_team_name           away_team_name  Pre-Match PPG (Home)  \
0                 Liverpool          West Ham United                  0.00   
1                 Liverpool   Brighton & Hove Albion                  3.00   
2                 Liverpool              Southampton                  3.00   
3                 Liverpool          Manchester City                  3.00   
4                 Liverpool             Cardiff City                  2.50   
5                 Liverpool                   Fulham                  2.60   
6                 Liverpool                  Everton                  2.67   
7                 Liverpool        Manchester United                  2.71   
8                 Liverpool         Newcastle United                  2.75   
9                 Liverpool           Crystal Palace                  2.80   
10                Liverpool           Leicester City                  2.82   
11                Liverpool          AFC Bournemouth                  2.67   
12                Liverpool                  Watford                  2.69   
13                Liverpool                  Burnley                  2.71   
14                Liverpool        Tottenham Hotspur                  2.73   
15                Liverpool                  Chelsea                  2.75   
16                Liverpool        Huddersfield Town                  2.76   
17                Liverpool  Wolverhampton Wanderers                  2.78   
18                  Chelsea                  Arsenal                  0.00   
19             Cardiff City                  Arsenal                  1.00   
20         Newcastle United                  Arsenal                  0.00   
21                   Fulham                  Arsenal                  1.00   
22           Crystal Palace                  Arsenal                  0.25   
23          AFC Bournemouth                  Arsenal                  1.83   
24        Manchester United                  Arsenal                  1.83   
25              Southampton                  Arsenal                  0.71   
26   Brighton & Hove Albion                  Arsenal                  1.75   
27          West Ham United                  Arsenal                  1.27   
28          Manchester City                  Arsenal                  2.75   
29        Huddersfield Town                  Arsenal                  0.38   
30        Tottenham Hotspur                  Arsenal                  2.08   
31                  Everton                  Arsenal                  1.56   
32                  Watford                  Arsenal                  1.73   
33  Wolverhampton Wanderers                  Arsenal                  1.65   
34           Leicester City                  Arsenal                  1.35   
35                  Burnley                  Arsenal                  1.28   

    Pre-Match PPG (Away)  home_ppg  away_ppg  home_team_goal_count  \
0                   0.00      2.79      1.11                     4   
1                   0.00      2.79      0.68                     1   
2                   1.50      2.79      0.84                     3   
3                   2.33      2.79      2.32                     0   
4                   0.25      2.79      0.74                     4   
5                   0.17      2.79      0.26                     2   
6                   1.00      2.79      1.05                     1   
7                   1.38      2.79      1.58                     3   
8                   1.25      2.79      1.05                     4   
9                   1.18      2.79      1.53                     4   
10                  1.42      2.79      1.32                     1   
11                  0.75      2.79      0.84                     3   
12                  1.43      2.79      1.21                     5   
13                  0.87      2.79      0.89                     4   
14                  2.06      2.79      1.74                     2   
15    

In [7]:
test = pd.read_csv('test.csv')
test

home_team_name away_team_name  Pre-Match PPG (Home)  Pre-Match PPG (Away)  \
0      Liverpool        Arsenal                  2.78                  1.67   

   home_ppg  away_ppg  home_team_goal_count  away_team_goal_count  \
0      2.79      1.32                     5                     1   

   total_goal_count  total_goals_at_half_time  ...  shots_home  \
0                 6                         5  ...         267   

   shots_on_target  shots_on_target_away  shots_on_target_home  fouls  \
0              264                   119                   145    315   

   fouls_home  xg_for_avg_overall  xg_for_avg_home  xg_for_avg_away  \
0         149                 1.9             2.12             1.67   

   Status_home_away  
0          Win_home  

[1 rows x 95 columns]

In [8]:
test['home_team_name'] = test['home_team_name'].astype('category')
test['away_team_name'] = test['away_team_name'].astype('category')
test['Status_home_away'] = test['Status_home_away'].astype('category')
test['Defence_line'] = test['Defence_line'].astype('category')
test['Home_ground_effect'] = test['Home_ground_effect'].astype('category')
test['Tempo_home'] = test['Tempo_home'].astype('category')
test['Tempo'] = test['Tempo'].astype('category')
test['Transition_Defence_Attack'] = test['Transition_Defence_Attack'].astype('category')
test['stadium_name'] = test['stadium_name'].astype('category')
cat_columns = test.select_dtypes(['category']).columns
test[cat_columns] = test[cat_columns].apply(lambda x: x.cat.codes)
test 

home_team_name  away_team_name  Pre-Match PPG (Home)  Pre-Match PPG (Away)  \
0               0               0                  2.78                  1.67   

   home_ppg  away_ppg  home_team_goal_count  away_team_goal_count  \
0      2.79      1.32                     5                     1   

   total_goal_count  total_goals_at_half_time  ...  shots_home  \
0                 6                         5  ...         267   

   shots_on_target  shots_on_target_away  shots_on_target_home  fouls  \
0              264                   119                   145    315   

   fouls_home  xg_for_avg_overall  xg_for_avg_home  xg_for_avg_away  \
0         149                 1.9             2.12             1.67   

   Status_home_away  
0                 0  

[1 rows x 95 columns]

In [9]:
df['home_team_name'] = df['home_team_name'].astype('category')
df['away_team_name'] = df['away_team_name'].astype('category')
df['Status_home_away'] = df['Status_home_away'].astype('category')
df['Defence_line'] = df['Defence_line'].astype('category')
df['Home_ground_effect'] = df['Home_ground_effect'].astype('category')
df['Tempo_home'] = df['Tempo_home'].astype('category')
df['Tempo'] = df['Tempo'].astype('category')
df['Transition_Defence_Attack'] = df['Transition_Defence_Attack'].astype('category')
df['stadium_name'] = df['stadium_name'].astype('category')
cat_columns = df.select_dtypes(['category']).columns
df[cat_columns] = df[cat_columns].apply(lambda x: x.cat.codes)
df 

home_team_name  away_team_name  Pre-Match PPG (Home)  \
0               10              17                  0.00   
1               10               2                  3.00   
2               10              14                  3.00   
3               10              11                  3.00   
4               10               4                  2.50   
5               10               8                  2.60   
6               10               7                  2.67   
7               10              12                  2.71   
8               10              13                  2.75   
9               10               6                  2.80   
10              10              10                  2.82   
11              10               0                  2.67   
12              10              16                  2.69   
13              10               3                  2.71   
14              10              15                  2.73   
15              10               5                  2.75   
16              10               9                  2.76   
17              10              18                  2.78   
18               4               1                  0.00   
19               3               1                  1.00   
20              13               1                  0.00   
21               7               1                  1.00   
22               5               1                  0.25   
23               0               1                  1.83   
24              12               1                  1.83   
25              14               1                  0.71   
26               1               1                  1.75   
27              17               1                  1.27   
28              11               1                  2.75   
29               8               1                  0.38   
30              15               1                  2.08   
31               6               1                  1.56   
32              16               1                  1.73   
33              18               1                  1.65   
34               9               1                  1.35   
35               2               1                  1.28   

    Pre-Match PPG (Away)  home_ppg  away_ppg  home_team_goal_count  \
0                   0.00      2.79      1.11                     4   
1                   0.00      2.79      0.68                     1   
2                   1.50      2.79      0.84                     3   
3                   2.33      2.79      2.32                     0   
4                   0.25      2.79      0.74                     4   
5                   0.17      2.79      0.26                     2   
6                   1.00      2.79      1.05                     1   
7                   1.38      2.79      1.58                     3   
8                   1.25      2.79      1.05                     4   
9                   1.18      2.79      1.53                     4   
10                  1.42      2.79      1.32                     1   
11                  0.75      2.79      0.84                     3   
12                  1.43      2.79      1.21                     5   
13                  0.87      2.79      0.89                     4   
14                  2.06      2.79      1.74                     2   
15                  1.75      2.79      1.58                     2   
16                  0.35      2.79      0.37                     5   
17                  1.28      2.79      1.21                     2   
18                  0.00      2.21      1.32                     3   
19                  0.00      1.05      1.32                     2   
20                  1.50      1.32      1.32                     1   
21                  2.00      1.11      1.32                     1   
22                  2.25      1.05      1.32                     2   
23                  2.00      1.53      1.32                     1   
24                  2.17      1.8

In [10]:
test_X = test.drop(['Status_home_away'], axis=1)
test_X


home_team_name  away_team_name  Pre-Match PPG (Home)  Pre-Match PPG (Away)  \
0               0               0                  2.78                  1.67   

   home_ppg  away_ppg  home_team_goal_count  away_team_goal_count  \
0      2.79      1.32                     5                     1   

   total_goal_count  total_goals_at_half_time  ...  shots_away  shots_home  \
0                 6                         5  ...         205         267   

   shots_on_target  shots_on_target_away  shots_on_target_home  fouls  \
0              264                   119                   145    315   

   fouls_home  xg_for_avg_overall  xg_for_avg_home  xg_for_avg_away  
0         149                 1.9             2.12             1.67  

[1 rows x 94 columns]

In [11]:
X = df.drop(['Status_home_away'], axis=1)
Y = df['Status_home_away']

X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.1)

In [33]:
## Training Model
model1 = DecisionTreeClassifier(random_state=1)
model1.fit(X_train, y_train)

DecisionTreeClassifier(random_state=1)

In [47]:
import pickle

# serialize the model
model_bytes = pickle.dumps(model1)
print(model_bytes)
print(len(model_bytes))

b'\x80\x03csklearn.tree._classes\nDecisionTreeClassifier\nq\x00)\x81q\x01}q\x02(X\t\x00\x00\x00criterionq\x03X\x04\x00\x00\x00giniq\x04X\x08\x00\x00\x00splitterq\x05X\x04\x00\x00\x00bestq\x06X\t\x00\x00\x00max_depthq\x07NX\x11\x00\x00\x00min_samples_splitq\x08K\x02X\x10\x00\x00\x00min_samples_leafq\tK\x01X\x18\x00\x00\x00min_weight_fraction_leafq\nG\x00\x00\x00\x00\x00\x00\x00\x00X\x0c\x00\x00\x00max_featuresq\x0bNX\x0e\x00\x00\x00max_leaf_nodesq\x0cNX\x0c\x00\x00\x00random_stateq\rK\x01X\x15\x00\x00\x00min_impurity_decreaseq\x0eG\x00\x00\x00\x00\x00\x00\x00\x00X\x0c\x00\x00\x00class_weightq\x0fNX\t\x00\x00\x00ccp_alphaq\x10G\x00\x00\x00\x00\x00\x00\x00\x00X\x0e\x00\x00\x00n_features_in_q\x11K^X\n\x00\x00\x00n_outputs_q\x12K\x05X\x08\x00\x00\x00classes_q\x13]q\x14(cnumpy.core.multiarray\n_reconstruct\nq\x15cnumpy\nndarray\nq\x16K\x00\x85q\x17C\x01bq\x18\x87q\x19Rq\x1a(K\x01K\x02\x85q\x1bcnumpy\ndtype\nq\x1cX\x02\x00\x00\x00f4q\x1d\x89\x88\x87q\x1eRq\x1f(K\x03X\x01\x00\x00\x00<q NNNJ\xf

In [13]:
## Testing Model
y_pred = model.predict_proba(test_X)
y_pred

'Token f441d0e5aeeb44007531756377c675daa199593d'

array([[0., 0., 0., 0., 1.]])

In [14]:
X_test

home_team_name  away_team_name  Pre-Match PPG (Home)  \
2               10              14                  3.00   
11              10               0                  2.67   
1               10               2                  3.00   
7               10              12                  2.71   

    Pre-Match PPG (Away)  home_ppg  away_ppg  home_team_goal_count  \
2                   1.50      2.79      0.84                     3   
11                  0.75      2.79      0.84                     3   
1                   0.00      2.79      0.68                     1   
7                   1.38      2.79      1.58                     3   

    away_team_goal_count  total_goal_count  total_goals_at_half_time  ...  \
2                      0                 3                         3  ...   
11                     0                 3                         2  ...   
1                      0                 1                         1  ...   
7                      1                 4                         2  ...   

    shots_away  shots_home  shots_on_target  shots_on_target_away  \
2          205         267              264                   119   
11         205         267              264                   119   
1          205         267              264                   119   
7          205         267              264                   119   

    shots_on_target_home  fouls  fouls_home  xg_for_avg_overall  \
2                    145    315         149                 1.9   
11                   145    315         149                 1.9   
1                    145    315         149                 1.9   
7                    145    315         149                 1.9   

    xg_for_avg_home  xg_for_avg_away  
2              2.12             1.67  
11             2.12             1.67  
1              2.12             1.67  
7              2.12             1.67  

[4 rows x 94 columns]

In [ ]:
## Evaluating Model 
accuracy = accuracy_score(y_test, y_pred)
accuracy


In [16]:
### ML technique

X = df.drop(['Status_home_away'], axis=1)
Y = df['Status_home_away']

min_max_scaler = MinMaxScaler()
X_scale = min_max_scaler.fit_transform(X)

# encode class values as integers
encoder = LabelEncoder()
encoder.fit(Y)
encoded_Y = encoder.transform(Y)
# convert integers to dummy variables (i.e. one hot encoded)
dummy_y = to_categorical(encoded_Y)
print(dummy_y.shape)
print(dummy_y)

(36, 5)
[[0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 1.]
 [0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 1.]
 [0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0.]
 [1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 1. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 1. 0. 0.]]


In [17]:
X_train, X_test, y_train, y_test = train_test_split(X_scale, dummy_y, test_size=0.1)

print(X_train.shape)
print(y_train.shape)

(32, 94)
(32, 5)


In [18]:
#from tensorflow import keras 
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [19]:
model = Sequential([
    Dense(32, activation='relu', input_shape=(94,)),
    Dense(32, activation='relu'),
    Dense(5, activation='softmax'),
])


In [20]:
model.compile(optimizer='sgd',
              loss='categorical_crossentropy',
              metrics=['accuracy'])



In [26]:
hist = model.fit(X_train, y_train,
          batch_size=8, epochs=100,)

Epoch 1/100
1/4 [======>.......................] - ETA: 0s - loss: 0.6066 - accuracy: 0.7500

4/4 [==============================] - 0s 0s/step - loss: 0.6775 - accuracy: 0.7500
Epoch 2/100
4/4 [==============================] - 0s 5ms/step - loss: 0.6829 - accuracy: 0.7188
Epoch 3/100
4/4 [==============================] - 0s 0s/step - loss: 0.6746 - accuracy: 0.7500
Epoch 4/100
4/4 [==============================] - 0s 5ms/step - loss: 0.6762 - accuracy: 0.7500
Epoch 5/100
4/4 [==============================] - 0s 0s/step - loss: 0.6750 - accuracy: 0.7812
Epoch 6/100
4/4 [==============================] - 0s 5ms/step - loss: 0.6834 - accuracy: 0.7188
Epoch 7/100
4/4 [==============================] - 0s 0s/step - loss: 0.6671 - accuracy: 0.7812
Epoch 8/100
4/4 [==============================] - 0s 0s/step - loss: 0.6631 - accuracy: 0.7812
Epoch 9/100
4/4 [==============================] - 0s 0s/step - loss: 0.6636 - accuracy: 0.7812
Epoch 10/100
4/4 [==============================] - 0s 0s/step - loss: 0.6667 - accuracy: 0.7812
Epoch 11/100
4/4 [==============================

In [29]:
print(hist)

In [45]:
import pickle
import joblib

joblib.dump(model1, 'model1.pkl')

['model1.pkl']

In [22]:
min_max_scaler = MinMaxScaler()
test_scale = min_max_scaler.fit_transform(test_X)
print(test_scale.shape)

(1, 94)


In [25]:
preds = model.predict(test_scale)
print(preds)

[[0.19171613 0.16135928 0.2036482  0.26865768 0.17461878]]
